# -*- coding: utf-8 -*-
# Copyright: Damien Elmes <anki@ichi2.net>
# License: GNU GPL, version 3 or later; http://www.gnu.org/copyleft/gpl.html
#
# Fix decks with consecutive card/fact/field IDs generated by misbehaving
# plugins
#

from PyQt4.QtGui import *
from PyQt4.QtCore import *
from ankiqt import mw
from anki.utils import genID
from ankiqt.ui.utils import showInfo

def run():
    db = mw.deck.s
    mw.startProgress()
    # gather old ids
    data = []
    for id in db.column0("select id from facts"):
        data.append(dict(new=genID(), old=id))
    # update facts
    db.statements("update facts set id = :new where id = :old", data)
    # fields
    db.statements(
        "update fields set id = random(), factId = :new where factId = :old",
        data)
    # cards
    db.statements(
        "update cards set id = random(), factId = :new where factId = :old",
        data)
    mw.finishProgress()
    mw.deck.setModified()
    mw.deck.save()
    showInfo("Done.")

a = QAction(mw)
a.setText("Fix IDs")
mw.mainWin.menuTools.addAction(a)
mw.connect(a, SIGNAL("triggered()"), run)
